### ISSUE TITLE
[1.19] Server side crash. 

### ISSUE THREAD

**Issue by AzureDoom** [Alex-the-666/DomesticationInnovation#60]
```
[08.07 13:31:27] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: alexsmobs, class com.github.alexthe666.alexsmobs.AlexsMobs
[08.07 13:31:27] [Server] java.lang.reflect.InvocationTargetExceptionnull
[08.07 13:31:27] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[08.07 13:31:27] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[08.07 13:31:27] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[08.07 13:31:27] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[08.07 13:31:27] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.64.jar%23107!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.64.jar%23106!/:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[08.07 13:31:27] [Server] Caused byjava.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER
[08.07 13:31:27] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19-41.0.64.jar%2365!/:1.{}
[08.07 13:31:27] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.1.jar%2353!/:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.1.jar%2353!/:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.1.jar%2353!/:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[08.07 13:31:27] [Server] 	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:239) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:231) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:186) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:180) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:174) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at com.github.alexthe666.alexsmobs.AlexsMobs.<init>(AlexsMobs.java:84) ~[alexsmobs-1.19.1.jar%2395!/:1.19.{re:classloading}
[08.07 13:31:27] [Server] 	... more
[08.07 13:31:27] [Server] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 41.0.64, for MC 1.19 with MCP 20220607.102129
[08.07 13:31:27] [Server] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v41.0.64 Initialized
[08.07 13:31:27] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER
[08.07 13:31:27] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: domesticationinnovation, class com.github.alexthe668.domesticationinnovation.DomesticationMod
[08.07 13:31:27] [Server] java.lang.reflect.InvocationTargetExceptionnull
[08.07 13:31:27] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[08.07 13:31:27] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[08.07 13:31:27] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[08.07 13:31:27] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[08.07 13:31:27] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.64.jar%23107!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.64.jar%23106!/:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {}
[08.07 13:31:27] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[08.07 13:31:27] [Server] Caused byjava.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER
[08.07 13:31:27] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19-41.0.64.jar%2365!/:1.{}
[08.07 13:31:27] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.1.jar%2353!/:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.1.jar%2353!/:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.1.jar%2353!/:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.0.3.jar:?] {}
[08.07 13:31:27] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[08.07 13:31:27] [Server] 	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?] {re:mixin}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:239) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:231) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:186) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:180) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:174) ~[eventbus-6.0.0.jar%2350!/:?] {}
[08.07 13:31:27] [Server] 	at com.github.alexthe668.domesticationinnovation.DomesticationMod.<init>(DomesticationMod.java:50) ~[domesticationinnovation-1.5.1-1.19.jar%2398!/:1.5.1-1.{re:mixin,re:classloading}
```
1.19 is just fun.

**Comment by Alex-the-666** [comment]
fix should be out today
